#!/usr/bin/env python3
"""Industry and geography priors for review-revenue-estimator."""
from __future__ import annotations

from typing import Any


INDUSTRY_DEFAULTS: dict[str, dict[str, Any]] = {
    "qsr": {
        "review_rate": (0.004, 0.007, 0.012),
        "ticket": (8, 13, 20),
        "label": "Quick-service restaurant",
        "turns_per_day": 4.0,
        "capacity_unit": "seats",
    },
    "cafe": {
        "review_rate": (0.004, 0.007, 0.012),
        "ticket": (7, 12, 18),
        "label": "Cafe / coffee / bakery",
        "turns_per_day": 6.0,
        "capacity_unit": "seats",
    },
    "full_service_restaurant": {
        "review_rate": (0.005, 0.009, 0.018),
        "ticket": (22, 38, 60),
        "label": "Full-service restaurant",
        "turns_per_day": 2.2,
        "capacity_unit": "seats",
    },
    "fine_dining": {
        "review_rate": (0.010, 0.018, 0.030),
        "ticket": (70, 120, 200),
        "label": "Fine dining",
        "turns_per_day": 1.2,
        "capacity_unit": "seats",
    },
    "bar": {
        "review_rate": (0.004, 0.008, 0.015),
        "ticket": (12, 22, 40),
        "label": "Bar / nightlife",
        "turns_per_day": 3.0,
        "capacity_unit": "seats",
    },
    "restaurants": {
        "review_rate": (0.005, 0.010, 0.020),
        "ticket": (25, 45, 70),
        "label": "Restaurants / cafes / bars (umbrella)",
        "turns_per_day": 2.5,
        "capacity_unit": "seats",
    },
    "salon": {
        "review_rate": (0.02, 0.04, 0.08),
        "ticket": (40, 75, 130),
        "label": "Hair salon / barber",
        "turns_per_day": 6.0,
        "capacity_unit": "chairs",
    },
    "spa": {
        "review_rate": (0.02, 0.045, 0.08),
        "ticket": (80, 140, 250),
        "label": "Spa / medspa",
        "turns_per_day": 5.0,
        "capacity_unit": "chairs",
    },
    "gym": {
        "review_rate": (0.004, 0.008, 0.015),
        "ticket": (30, 55, 90),
        "label": "Gym / fitness (monthly dues as ticket)",
        "turns_per_day": None,
        "capacity_unit": "members",
    },
    "personal_care": {
        "review_rate": (0.02, 0.04, 0.08),
        "ticket": (50, 80, 120),
        "label": "Personal care (umbrella)",
        "turns_per_day": 5.0,
        "capacity_unit": "chairs",
    },
    "home_services": {
        "review_rate": (0.03, 0.055, 0.09),
        "ticket": (180, 320, 550),
        "label": "Home services / contractors",
        "turns_per_day": 2.0,
        "capacity_unit": "crews",
    },
    "hvac": {
        "review_rate": (0.04, 0.07, 0.11),
        "ticket": (220, 400, 700),
        "label": "HVAC / plumbing / electrical",
        "turns_per_day": 3.0,
        "capacity_unit": "crews",
    },
    "house_cleaning": {
        "review_rate": (0.03, 0.06, 0.10),
        "ticket": (130, 220, 350),
        "label": "House cleaning",
        "turns_per_day": 4.0,
        "capacity_unit": "crews",
    },
    "medical": {
        "review_rate": (0.015, 0.035, 0.06),
        "ticket": (140, 240, 400),
        "label": "Medical / clinic",
        "turns_per_day": 8.0,
        "capacity_unit": "rooms",
    },
    "dental": {
        "review_rate": (0.02, 0.04, 0.07),
        "ticket": (180, 280, 450),
        "label": "Dental",
        "turns_per_day": 8.0,
        "capacity_unit": "chairs",
    },
    "vet": {
        "review_rate": (0.02, 0.045, 0.08),
        "ticket": (120, 220, 380),
        "label": "Veterinary",
        "turns_per_day": 8.0,
        "capacity_unit": "rooms",
    },
    "professional": {
        "review_rate": (0.015, 0.035, 0.06),
        "ticket": (200, 450, 900),
        "label": "Professional services",
        "turns_per_day": 3.0,
        "capacity_unit": "staff",
    },
    "retail": {
        "review_rate": (0.003, 0.006, 0.012),
        "ticket": (25, 60, 140),
        "label": "Retail (brick-and-mortar)",
        "turns_per_day": None,
        "capacity_unit": None,
    },
    "auto_services": {
        "review_rate": (0.04, 0.065, 0.10),
        "ticket": (280, 480, 750),
        "label": "Auto services / repair",
        "turns_per_day": 3.0,
        "capacity_unit": "bays",
    },
    "hotels": {
        "review_rate": (0.03, 0.06, 0.10),
        "ticket": (110, 170, 280),
        "label": "Hotels / lodging (ticket ≈ ADR × stay length ~1.3–1.8)",
        "turns_per_day": None,
        "capacity_unit": "rooms",
    },
    "default": {
        "review_rate": (0.03, 0.055, 0.08),
        "ticket": (80, 150, 300),
        "label": "Other / unknown",
        "turns_per_day": None,
        "capacity_unit": None,
    },
}

ALIASES = {
    "restaurant": "full_service_restaurant",
    "fsr": "full_service_restaurant",
    "quick_service": "qsr",
    "fast_food": "qsr",
    "coffee": "cafe",
    "bakery": "cafe",
    "fine": "fine_dining",
    "nightlife": "bar",
    "hair": "salon",
    "barber": "salon",
    "fitness": "gym",
    "contractor": "home_services",
    "contractors": "home_services",
    "plumber": "hvac",
    "plumbing": "hvac",
    "electrician": "hvac",
    "cleaning": "house_cleaning",
    "clinic": "medical",
    "dentist": "dental",
    "veterinary": "vet",
    "lawyer": "professional",
    "legal": "professional",
    "accounting": "professional",
    "auto": "auto_services",
    "auto_repair": "auto_services",
    "hotel": "hotels",
    "lodging": "hotels",
    "bnb": "hotels",
}

LOCATION_ADJUST = {
    "major_metro": {"ticket": 1.25, "rate": 1.15},
    "secondary_city": {"ticket": 1.10, "rate": 1.05},
    "suburban": {"ticket": 1.00, "rate": 1.00},
    "rural": {"ticket": 0.85, "rate": 0.85},
}
